title: Zach Olkin
description: PhD Student in Controls + Dynamical Systems | Caltech
show_download: false


theme: minima

minima:
  skin: dark

header_pages:
  - about.md

#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme